### ISSUE TITLE
Add task-launcher tests for PCF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#107]
As a developer, I'd like to add e2e acceptance coverage for launching tasks via a stream in PCF.

**Acceptance:**
- Assert maven resource is supported.
- Assert stream deployment and task launch states.
- Verify that the stream actually launches the task.
- Assert task's exit code is 0.

**Comment by cppwfs** [comment]
The following Stories must be completed and merged first:
https://github.com/spring-cloud-stream-app-starters/tasklauncher-cloudfoundry/issues/12
https://github.com/spring-cloud/spring-cloud-task/issues/321

**Comment by dturanski** [comment]
Complete via #350
