### ISSUE TITLE
Review cleanup order for CF tests

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#118]
While reviewing the logs from the [last CI run](https://build.spring.io/browse/SCD-ATCF-42/log), it seems like the failure cause is due to the order in which we cleanup resources. 

```
05-Jul-2017 01:32:03	Deleting service rabbit in org scdf-ci / space scdf-acceptance-test as igopinathan@pivotal.io...
05-Jul-2017 01:32:04	FAILED
05-Jul-2017 01:32:04	Cannot delete service instance, service keys and bindings must first be deleted
```

**Comment by trisberg** [comment]
Could also be some orphaned stream app that is bound to the rabbit service, we delete the server before deleting the services, so it must be something else interfering.

**Comment by trisberg** [comment]
I cleaned up the orphaned stream apps and kicked off the build again.

I added a step before the tests to clean out the environment from any left over servers/apps in the k8s tests, we should do that for cf as well.
