### ISSUE TITLE
Extract Fluent APIs and move it to SCDF core

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#121]
As a developer, I'd like to extract Fluent API and move it SCDF Core, so it is a reusable artifact for automation scenarios. See example [here](https://github.com/kbastani/event-stream-processing-microservices/blob/master/platform-services/data-flow-server/src/main/java/demo/ImportResources.java#L35).

**Acceptance:**
DSL module is extracted and moved to SCDF Core. The acceptance-tests include that as a dependency.

**Comment by viniciusccarvalho** [comment]
This has already been merged into core via https://github.com/spring-cloud/spring-cloud-dataflow/commit/e1de24f639544aeebc1c7c60437b37d7422a268f
