### ISSUE TITLE
Investigate why K8S AT is green even without roles/role-bindings

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#146]
As a developer, I'd like to investigate how the K8S ATs is green even when the role/role-binding is not configured for the SCDF-server.

RBAC Cluster: Cepheus
CI: https://build.spring.io/browse/SCD-ATK8S

Whatever we find out, it might also feed into spring-cloud/spring-cloud-dataflow-acceptance-tests#145

**Comment by sabbyanandan** [comment]
As an update, when I manually ran the Classic ATs, I get the same errors that we see for the Skipper ATs, so that's consistent at least. Oh, btw, the CI is not green anymore. :)

```
30-Jan-2018 04:34:54	Failed to connect to 35.197.101.117:80. Attempt  #18/20... will try again in [15] seconds
30-Jan-2018 04:35:10	Failed to connect to 35.197.101.117:80. Attempt  #19/20... will try again in [15] seconds
30-Jan-2018 04:35:25	Failed to connect to 35.197.101.117:80. Attempt  #20/20... will try again in [15] seconds
```

See full-logs [here](https://build.spring.io/browse/SCD-ATK8S-273/log).

**Comment by viniciusccarvalho** [comment]
They were green because someone has already manually created the roles and bindings
