### ISSUE TITLE
Remove use of bit.ly links as they have rate limits

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#155]
Causes CI failures.  Use direct links of apps/tasks

**Comment by sabbyanandan** [comment]
Similar to what has been done in [Core](https://github.com/spring-cloud/spring-cloud-dataflow/commit/319cf03c18ee2b3adbbc2099c2d5d2d178e3b1ae), we will have to adjust the infrastructure to replace the bit.ly links with Spring repo URLs. 

Celsius.SR1: http://repo.spring.io/libs-release/org/springframework/cloud/stream/app/spring-cloud-stream-app-descriptor/Celsius.SR1/
Clark.GA: http://repo.spring.io/libs-snapshot/org/springframework/cloud/task/app/spring-cloud-task-app-descriptor/Clark.RELEASE/

We will have to also update the README to replace the bit.ly references with the Spring repo URLs.
