### ISSUE TITLE
Add end-to-end config-server integration tests for CF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#16]
As a developer, I'd like to automate e2e integration of config-server with the server and apps.

**Acceptance:**

- Server
  - Verify bootstrapping the server with default logging level (from config-server) is set as INFO
  - Verify resolving security properties from config-server
- Apps
  - Verify http-source port is resolved as 9009 from config-server
  - Verify time-source trigger is set to as 5s from config-server
  - Verify log-sink log level is set to DEBUG from config-serve

**Comment by trisberg** [comment]
Latest changes broke the CI build it seems - https://build.spring.io/browse/SCD-ATCF-104

From the server log:
```
Aug 22 07:08:04 scdf-ci.scdf-acceptance-test.scdf-server 87198297-f91a-4c52-ba8e-01abee70e4cd/[APP/PROC/WEB/0]: 2017-08-22 14:08:04.622 ERROR 32 --- [ry-client-nio-1] o.s.c.d.s.c.CloudFoundryAppDeployer      : Error creating app scdf-server-HTTP-DESTINATION-SOURCE-http.  Exception Message CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance cloud-config-server is in progress. 
Aug 22 07:08:04 scdf-ci.scdf-acceptance-test.scdf-server 87198297-f91a-4c52-ba8e-01abee70e4cd/[APP/PROC/WEB/0]: 2017-08-22 14:08:04.624 ERROR 32 --- [ry-client-nio-1] o.s.c.d.s.c.CloudFoundryAppDeployer      : Failed to deploy scdf-server-HTTP-DESTINATION-SOURCE-http 
Aug 22 07:08:04 scdf-ci.scdf-acceptance-test.scdf-server 87198297-f91a-4c52-ba8e-01abee70e4cd/[APP/PROC/WEB/0]: org.cloudfoundry.client.v2.ClientV2Exception: CF-AsyncServiceInstanceOperationInProgress(60016): An operation for service instance cloud-config-server is in progress. 
```

**Comment by ilayaperumalg** [comment]
@trisberg This is because I am in the process of updating the existing `config-server` instance to use the properties from the `spring-cloud-dataflow-acceptance-tests` repo itself (based on the discussion from this PR). I will post the update once the changes are in sync.

**Comment by ilayaperumalg** [comment]
https://build.spring.io/browse/SCD-ATCF-104 is back to green.

Closing this ticket. 

We will create a `label` based config server properties so that those test properties wouldn't need to be on the top level of this project.
