### ISSUE TITLE
Revisit why are we starting the server, checking feature-toggles, and deleting it immediately 

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#160]
We are simply checking the feature toggle info from /about and killing the server. Immediately after this, we are re-downloading the server and starting it again. This is happening for the 1st time only and not for every test run.

**Comment by tzolov** [comment]
Apparently this block in `run.sh` script acts as a ConfigServer tests!! E.g. we are testing CC directly in the bash script rather than in dedicated integration tests. 
We should use this ticket (or create another) as requirement to migrate the CC test from bash to the integrations set.

**Comment by dturanski** [comment]
Apparently, this test is just checking that a property is set from config server if the `cloud1` profile is enabled.  Which proves only that the config server is configured properly (accessible from the test environment) and working properly (resolves app name and profile correctly) . Without questioning the value of this test, why can't we simply do something like this? https://gist.github.com/dturanski/7904a62225a96f2bd866b5c9ee8d160f

**Comment by dturanski** [comment]
Can we do something stupid like set a benign property in config server for the `default` profile like 
`spring.cloud.dataflow.version-info.dependencies.spring-cloud-dataflow-shell.name=Django`?  I tested this with local server.
