### ISSUE TITLE
Local: Add support to save the logs upon test failures

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#167]
As a developer, I'd like to add support to store the "app" logs in the drive as and when the tests fail. Right now, we only get the generic "Unable to start the Stream ..." message in the CI logs. We would want to use the stored log artifacts to inspect and troubleshoot the failure reasons manually.

**Comment by markpollack** [comment]
Same as issue #170 - just keep all the logs no matter if the test passes or fails
