### ISSUE TITLE
Create pre-condition to run CF tests a check for existence of config service

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#174]
The config service takes several minutes to create, so we run the tests assuming there is a service already created.

Add a check so that if the service is not running, there is a fail fast error message and the AT tests are not run.

**Comment by markpollack** [comment]
@dturanski has dome ideas on this.

**Comment by markpollack** [comment]
related to #160

**Comment by markpollack** [comment]
Given the approach of waiting for the mysql services , we could do the same with the config service.  depends on how long it takes.

**Comment by sabbyanandan** [comment]
We have decided to always reuse the same config-server SI on PAS. Nothing dynamic around confg-server tests.
