### ISSUE TITLE
Remove bamboo-group1 and bamboo-group2 separation from K8S plans

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#178]
As a developer, I'd like to remove `bamboo-group1` and `bamboo-group2` separation from the K8S CI plans, so we can run all the tests against the same namespace in 1-go.

The separation doesn't provide any benefit for us right now. There's no clash of conflicts either.

**Comment by chrisjs** [comment]
they are now consolidated to one group for rabbit and one for kafka. they still run namespace'd to keep them out of `default`

ive run all k8s at's for master and 1.5 and they seem to have run fine first try so looks good
