### ISSUE TITLE
Update ATs to Darwin SR2 coordinates

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#179]
As a developer, I'd like to update to point to the latest Darwin.GA App coordinates.

**Comment by sabbyanandan** [comment]
We may have to disable security for the 2.0 Apps to run the ATs. I believe the following property would do the exclusion. 

> spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration"

**Comment by sabbyanandan** [comment]
Also look for the new endpoint to resolve the logs.

**Comment by markpollack** [comment]
Several commits to address this issue

0c83aa4efad4b0e7540794d10f3ecde4f6a5a6d6
a9a09ff87ee37835378d2be8d567712e5ed546da
08e5bc520aba466c60a3788b41b49655670899b6
851fd562e5c8c03d8e55d3190a3c48862ba88254
