### ISSUE TITLE
Make it easy to se what versions of scdf/skipper and the apps are running

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#180]
As a developer, I'd like to study the applicability of Bamboo APIs, to we could possibly rely on the retrieved build logs to decide whether or not the plan is running successfully or if the correct version of the server/skipper/apps is in use and among many other things.

REST Docs: https://docs.atlassian.com/atlassian-bamboo/REST/5.5.0/

Maybe we could have a utility App that grep's the log files to look for:
 - test assertions
 - versions in use

**Comment by markpollack** [comment]
Switching to jenkins maybe the answer.

**Comment by sabbyanandan** [comment]
Not relevant anymore.
