### ISSUE TITLE
Run ATs against Skipper 1.1 BS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#182]
Run it against:
- [ ] local (pollack)
- [x] k8s (v1.10) (chris)
- [ ] cf (v2.0) (pollack)

**Comment by chrisjs** [comment]
master k8s at's are updated to 1.1.0.BUILD-SNAPSHOT and running now

**Comment by chrisjs** [comment]
looks like local and CF are pointing to 1.0.8.RELEASE based on the logs (i don't have access to those build plans) - so i've moved the k8s master AT's to point to 1.0.8.RELEASE as well
