### ISSUE TITLE
Run AT's against docker-compose setup

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow-acceptance-tests#195]
Try running AT's against DF running in docker compose as we show in the getting started guide. This would help catch failures faster (i.e.: upgrading apps/tasks) and find things that may or may not be supported (i.e.: the `http | log` example  didn't work as no ports were exposed).

**Comment by chrisjs** [comment]
tabling this for now per discussion

**Comment by tzolov** [comment]
Depends on spring-cloud/spring-cloud-dataflow/issues/3265

**Comment by tzolov** [comment]
Issue moved to [spring-cloud/spring-cloud-dataflow #3272](https://github.com/spring-cloud/spring-cloud-dataflow/issues/3272) via [**ZenHub**](https://www.zenhub.com/)
