### ISSUE TITLE
Need to disable actuator security on apps being tested

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-acceptance-tests#20]
Currently the apps started as a part of acceptance test streams are interrogated by the acceptance tests to verify that they are working as expected via the actuator endpoints.  (i.e. logs etc).   The actuator endpoint security needs to be disabled.  i.e. 
```
security.basic.enabled=false
management.security.enabled=false
``` 
or with the dev profile when deploying the  streams.

**Comment by artembilan** [comment]
OTOH it's not so difficult to use the declared Spring Boot credentials:
```
		@Autowired
		private SecurityProperties securityProperties;

		@Override
		@Before
		public void setup() {
			this.restTemplate = new TestRestTemplate(this.securityProperties.getUser().getName(),
				this.securityProperties.getUser().getPassword());
		}

```

**Comment by markpollack** [comment]
We have

```
		Map<String, String> streamProperties = new HashMap<>();
		streamProperties.put("app.*.logging.file", platformHelper.getLogfileName());
		streamProperties.put("app.*.endpoints.logfile.sensitive", "false");
		streamOperations.deploy(stream.getStreamName(), streamProperties);
```

as the way to get the log file, so this is issue is already address by the existing code base.
