### ISSUE TITLE
Switch to stream-latest and task-latest apps

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#205]
Need to pass 

```
--appsVersion Darwin.SR2 --tasksVersion Dearborn.SR1
```

Waiting on release of `Darwin.SR3` to fix issues with expression property used in router, transformer, and splitter.

**Comment by sabbyanandan** [comment]
We would have to upgrade to Darwin.SR3.

**Comment by markpollack** [comment]
Einstein/Dearborn should be set as the default now I believe.
