### ISSUE TITLE
Add Stream Content Type test

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-acceptance-tests#207]
Need to add an AT that verifies that content types as specified by dataflow for a stream are working as expected.    Something roughly like what is in our documentation.  `stream create tuple --definition "http | filter --inputType=application/x-spring-tuple | log" --deploy`

**Comment by markpollack** [comment]
I hope that `x-spring-tuple` is not in our docs!

**Comment by markpollack** [comment]
looks like there is, it should be changed to json.... maybe we should have an example that uses avro.

**Comment by markpollack** [comment]
Duplicate of #81?

**Comment by sabbyanandan** [comment]
Not relevant anymore.
