### ISSUE TITLE
Set spring.cloud.streamapp.security.enabled=false for ATs that need LogFile endpoint access is required

### ISSUE THREAD

**Issue by tzolov** [spring-cloud/spring-cloud-dataflow-acceptance-tests#211]
All 2.1.x app starters are provisioned with the [app-starters-security-commom](https://github.com/spring-cloud-stream-app-starters/core/tree/master/common/app-starters-security-common) by default. 
Later secures  the apps access by default, providing unauthorized access only to the `info` and `health` endpoints. 
Tests that need to access the `LogFile` or other endpoints, security have to disable the security applying the `spring.cloud.streamapp.security.enabled=false` property.

**Comment by markpollack** [comment]
This has been addressed in https://github.com/spring-cloud/spring-cloud-dataflow-acceptance-tests/commit/a69530d7072ae090156e0ba6a41cf3c3fb648de9
