### ISSUE TITLE
Adjust CF-tests / CI-plans to adapt to single-server

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#217]

**Comment by ilayaperumalg** [comment]
Following changes have been pushed to acceptance tests `master` to get this going:
commit 970c0821dc579b3e72ae0d957e1a266fde29ee63
commit 16f419723019e86e6706847a1342cacff18ce9bb
commit 46226e5f94c341be262a8edd310458e01b9bce2f
commit 92b9f0212386a883bfbcd992b342852e0cd3f73c
commit 784ff5d78c76a344235d2c995d04609bc2410497
commit 11da0a4cfcb8060b8eab4d2f11f080e852a835f1
commit f8fc1cad067f2119aaf540c6cbd76f283eb804b8

 The CI plans are also updated to have the corresponding changes.

**Comment by sabbyanandan** [comment]
All the CI plans have been corrected in reaction to single-server expectations.
