### ISSUE TITLE
Investigate whether dropping the database or the tables is possible in PAS

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#226]
As a developer, I'd like to explore options to study whether we can drop the database or the tables in entirety once after we run all the ATs.

This would simplify AT expectations for PAS at least.

**Comment by markpollack** [comment]
The motivation for this approach has been addressed by updating the AT scripts to poll for the creation of the supporting data base service.  Seems to be working just fine in practice.
