### ISSUE TITLE
Upgrade Kubernetes cluster versions (GKE/PKS)

### ISSUE THREAD

**Issue by chrisjs** [spring-cloud/spring-cloud-dataflow-acceptance-tests#239]
- [x] Modify GKE AT scripts to create a cluster before tests start and destroy the cluster when tests finish. If tests fail, the cluster will remain alive for manual inspection

- [x] Create two new PKS installations on GCP, one providing Kubernetes 1.12 and another providing 1.13. The existing PKS installation provides Kubernetes 1.11

- [x] Create one Kubernetes cluster on each of the new PKS installations

- [x] Update env spreadsheet

- [x] Validate AT's run on the created Kubernetes 1.12 and 1.13 clusters of the new PKS installations

**Comment by markpollack** [comment]
Ha, I was just looking to create this issue.  I'd suggest we try to sync with PKS `n-2` releases as well, though this will mean additional sprawl...

**Comment by chrisjs** [comment]
yea its a bit cumbersome in general, touches a few places etc.

in terms of PKS, in GKE we can create whatever cluster versions they support. with PKS one instance can only run a single cluster version - they all stay at the same version or get upgraded together.

the toolsmith env doesn't appear to let you select a target env, so if we want to have multiple k8s versions floating on PKS, looks like we would have to roll 2 of them on our own (and keep or upgrade the existing one).

**Comment by sabbyanandan** [comment]
The decision is to track n and upto n-2 releases in GKE and PKS. 

Also, we will repave K8s clusters on-demand for each AT run as opposed to leaving the cluster intact until we revise to support the upstream cluster versions.

**Comment by chrisjs** [comment]
checkboxes checked :1234:
