### ISSUE TITLE
Run ATs on GKE

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#267]
For each GKE env (1.11, 1.12, 1.13):

- [x]  Delegate ".cluster.domain" to GCP project / setup DNS / IP, etc.
- [x] Create wildcard cert for "*.clustername.domain"
- [x] Setup ingress 	   
- [x] Add/update Bamboo plan(s) as needed
- [ ] Ensure AT's run to completion from Bamboo

**Comment by chrisjs** [comment]
all 3 envs have green builds
