### ISSUE TITLE
Remove 'WhatToTest` configuration property and associated code

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#27]
Which tests will be run by specifying them as arguments to the maven command line, via `-Dtest=`

* AbstractStreamTests setup method should have the setup method cleaned up.
* Test clases do not need to override the `getTarget` method

similar for AbstractTaskTests

**Comment by cppwfs** [comment]
Just a side note.  We used the "What to Test" so that we could support groups of tests.  i.e. CORE tests, Stream Starters, Tasks etc.  This was to support users who wanted to run a suite of tests versus individual or All.
