### ISSUE TITLE
Enable CF ATs for master/2.3BS on Violet

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#277]
The CI plan for CF is disabled and the ATs haven't run in a few weeks. A glaring server-start issue creeped up in the meantime (see: https://github.com/spring-cloud/spring-cloud-dataflow/issues/3546).

**Comment by sabbyanandan** [comment]
For on-demand services like Rabbit and MySQL, we won't have the luxury to create/destroy them at will anymore because they are provisioned onto a brand new VM on each creation, which takes 10mins or so to get up and to run. Possibly a similar time also when deleting the SI.

Perhaps we could switch the AT strategy to _reuse_ the existing Rabbit and MySQL SIs as opposed to deleting/creating for each AT run. It would speed up the test run cycle. 

A caveat, however, is that the existing data in Rabbit and MySQL might continue to grow, so we may have to think about a cleanup routine when reusing the existing SIs.

**Comment by ilayaperumalg** [comment]
Add the script to clean up only the server components upon exit and this will help our ATs on CF run against the existing CF services.
