### ISSUE TITLE
ticktock tests do no assert that a 'tick' has been recieved in the log

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#28]
`waitForLogEntry(stream.getSink(), "] log.sink");`

is not a sufficient condition.  Need to poll the log and wait for tick messages to appear.

**Comment by markpollack** [comment]
oops, my bad, 

```
2017-05-11 21:53:42.510  INFO 28783 --- [time.ticktock-1] log-sink                                 : 05/11/17 21:53:42
```
is an entry in the log

**Comment by markpollack** [comment]
turns out that the current assertion is based on the thread name.  We can perhaps shift to testing the value of 

```
log-sink                                 : 05/11/17 21:53:42
```
is in the file - `log-sink` is the application name, but is something else on pcf based on stream def.....

**Comment by trisberg** [comment]
we should control the log output so we know what to search for

relates to #67
