### ISSUE TITLE
Include tests that can create cycles in the graph

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#323]

**Comment by cppwfs** [comment]
While the UI gives the user the ability move the arrows to create a cycle, the DSL that is generated is incorrect as shown here: ![image](https://user-images.githubusercontent.com/695673/106633763-1ab6b200-654d-11eb-8330-50d6c510a1f5.png)
When the user attempts to create the Composed Task the server will thrown an exception and the UI will report an error back to the user.   This is a UI issue where a user should not be allowed to move the exit arrow to a previous stage in the graph.

**Comment by cppwfs** [comment]
While the UI gives the user the ability move the arrows to create a cycle, the DSL that is generated is incorrect as shown here: ![image](https://user-images.githubusercontent.com/695673/106633763-1ab6b200-654d-11eb-8330-50d6c510a1f5.png)
When the user attempts to create the Composed Task the server will throw an exception and the UI will report an error back to the user.   This is a UI issue where a user should not be allowed to move the exit arrow to a previous stage in the graph.
