### ISSUE TITLE
AT plan with Apps 2.x and 3.x

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-acceptance-tests#343]

**Comment by tzolov** [comment]
* All ATs (https://build.spring.io/browse/SCDT) plans are configured to test both 2.x and 3.x stream apps.
* All obsolete ATs are moved from the ATs project (https://build.spring.io/browse/SCDT) to a dedicated ATs-Attic project: https://build.spring.io/browse/SATA
