### ISSUE TITLE
Test for 'local' platform's required env vars upfront

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-acceptance-tests#46]
Should test that `JAVA_HOME` and `DOCKER_SERVER` are set

**Comment by cppwfs** [comment]
Only check DOCKER_SERVER is set if using docker.  i.e. if testing a local instance and services are already running it would not be necessary to check for DOCKER.

**Comment by trisberg** [comment]
`./run.sh -p local -s -t` fails without `DOCKER_SERVER` being set, so something is off

**Comment by trisberg** [comment]
plus we don't have a way to test for local services reliably

**Comment by cppwfs** [comment]
Hmm... Just ran it locally (OSX) and DOCKER_SERVER was not present in the environment and it worked.

**Comment by trisberg** [comment]
removed the test for it in PR #45

**Comment by trisberg** [comment]
so all we need to test for now is JAVA_HOME
