### ISSUE TITLE
Create infrastructure for CI of acceptance tests against local installation

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-acceptance-tests#5]

**Comment by cppwfs** [comment]
This already exists here: https://jenkins.spring.io/job/Spring%20Cloud%20Data%20Flow%20Acceptance%20Test%20Multi/

**Comment by sabbyanandan** [comment]
As Glenn pointed out, we already have CI infrastructure for local-server.
