### ISSUE TITLE
Tests will fail without the setup phase

### ISSUE THREAD

**Issue by viniciusccarvalho** [spring-cloud/spring-cloud-dataflow-acceptance-tests#56]
This may not be a bug. But Tests will fail if the setup phase is not executed. The advantage of not running the setup phase is that it will save time and for reruns it does not make sense.

We could perhaps just make it clearer to users what env vars need to be present in order the tests to run:
$SERVER_URI (all)
$PLATFORM_TYPE (all)

if those are present there's no need to run the tests.

We could use a hidden file like `.config.properties` that setup generates and hence when running with -s it would just look for that file and use the `load_file` function.

**Comment by markpollack** [comment]
Certainly documenting what env-vars need to be set for the tests to run is important.  

I think we can assume some default for the local version, which is probably the getting started experience most users will go through.

**Comment by markpollack** [comment]
`TestConfigurationProperties` has 

```
	private String serverUri = "http://localhost:9393";

	private String platformType = "local";
```
as defaults.  I will provide defaults for streamRegistrationResource and taskRegistrationResource as we discussed in the office.
